# Generated by Django 4.2.4 on 2023-09-26 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_body', models.TextField(verbose_name='сообщение')),
                ('message_theme', models.CharField(max_length=150, verbose_name='тема сообщения')),
                ('content_creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='создатель текста')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='MessageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='назначенное время старта расслыки')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='время рассылки')),
                ('periodicity', models.CharField(choices=[('daily', 'Ежедневно'), ('weekly', 'Раз в неделю'), ('monthly', 'Раз в месяц')], default='daily', max_length=20, verbose_name='переодичность')),
                ('status', models.CharField(choices=[('created', 'Создана'), ('started', 'Запущены'), ('done', 'Завершена')], default='created', max_length=20, verbose_name='статус')),
                ('message_counter', models.IntegerField(default=0, verbose_name='счетчик')),
                ('day_to_send', models.IntegerField(blank=True, default=7, null=True, verbose_name='Кол-во дней для отправки')),
                ('content_creator', models.CharField(blank=True, max_length=50, null=True, verbose_name='создатель рассылки')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.clients', verbose_name='клиент')),
                ('message_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.message', verbose_name='message_id')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.AddField(
            model_name='message',
            name='settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsletter.messagesettings', verbose_name='Настройка'),
        ),
    ]
