# Generated by Django 4.2.4 on 2023-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0003_messagesettings_message_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagesettings',
            name='content_creator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='создатель клиента'),
        ),
    ]
