# Generated by Django 4.2.4 on 2023-09-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0004_messagesettings_content_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='content_creator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='создатель текста'),
        ),
        migrations.AlterField(
            model_name='messagesettings',
            name='content_creator',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='создатель рассылки'),
        ),
    ]
