# Generated by Django 4.2.4 on 2023-09-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='время попытки')),
                ('status', models.BooleanField(default=False, verbose_name='статус попытки')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='ответ сервиса')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
            },
        ),
    ]
