# Generated by Django 4.2.4 on 2023-09-22 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('newsletter', '0001_initial'),
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logs',
            name='newsletter',
            field=models.ForeignKey(on_delete=models.SET('рассылка удалена'), to='newsletter.newslettersettings', verbose_name='рассылка'),
        ),
    ]
